#ifndef _SYSCALLS_H_
#define _SYSCALLS_H_

enum syscalls_call {
	SYS_READ = 0,
	SYS_WRITE = 1,
	SYS_TERMINAL_CLEAR = 2,
	SYS_TERMINAL_SET = 3,
	SYS_TERMINAL_COLOR = 4,
	SYS_TIME_READ = 5,
	SYS_TIME_WRITE = 6,
	SYS_SCREENSAVER_ENABLE = 7,
	SYS_SCREENSAVER_TIME = 8,
	SYS_SCREENSAVER = 9
};

// WRITE-READ
#define ERROR_FILEDESCRIPTOR 1
// ^^ WRITE-READ ^^

// SCREEN SAVER
#define SCREENSAVER_TIME_MIN 5
#define ERROR_SCREENSAVER_TIME 1
// ^^ SCREEN SAVER ^^

#endif