#ifndef _VIDEO_COLORS_H_
#define _VIDEO_COLORS_H_

#define COLOR_BLACK 0x00
#define COLOR_GRAY 0x08
#define COLOR_DEFAULT 0x07
#define COLOR_PRIMARY 0x09
#define COLOR_SUCCESS 0x02
#define COLOR_ERROR 0x0C
#define COLOR_WARNING 0x0E
#define COLOR_WHITE 0x0F

#define BACKGROUND_DEFAULT 0x00
#define BACKGROUND_WHITE 0xF0
#define BACKGROUND_ERROR_LIGHT 0xC0
#define BACKGROUND_ERROR 0x40
#define BACKGROUND_SUCCESS_LIGHT 0xA0
#define BACKGROUND_SUCCESS 0x20
#define BACKGROUND_BLUE_LIGHT 0x90
#define BACKGROUND_BLUE 0x10
#define BACKGROUND_GRAY_LIGHT 0x70
#define BACKGROUND_GRAY 0x80
#define BACKGROUND_WARNING 0xE0
#define BACKGROUND_ORANGE 0x60

#endif