#ifndef _SYS_SCREEN_H_
#define _SYS_SCREEN_H_

#include <colors.h>

#define _TERMINAL_OPERATION_INVALID -1
#define _TERMINAL_OPERATION_ERROR -2

enum terminal_color_ops {
	_TERMINAL_COLOR_OPERATION_TEXT = 0,
	_TERMINAL_COLOR_OPERATION_BG,
	_TERMINAL_COLOR_OPERATION_STYLE,
};

#endif
