#ifndef _SYS_SCREEN_H_
#define _SYS_SCREEN_H_

#define SYSTEM_TERMINAL_MAX 1
#define SYSTEM_TERMINAL_COLOR_MIN 0x0
#define SYSTEM_TERMINAL_COLOR_MAX 0xF

#define SYSTEM_SCREENSAVER_TIME_MIN 5

enum sys_screen_errors {
	SYSTEM_ERROR_SCREENSAVER_TIME = -3,
	SYSTEM_ERROR_TERMINAL_INVALID = -2,
	SYSTEM_ERROR_TERMINAL_COLOR_INVALID = -1
};

#endif